#!/bin/bash
java -jar $CLOSURE_JAR --language_in ECMASCRIPT5 \
--compilation_level WHITESPACE_ONLY \
--js ./lf_core.js \
--js ./jsBindings/offsets.js \
--js ./jsBindings/Common/b2Math.js \
--js ./jsBindings/Collision/b2Collision.js \
--js ./jsBindings/Collision/Shapes/b2EdgeShape.js \
--js ./jsBindings/Collision/Shapes/b2PolygonShape.js \
--js ./jsBindings/Collision/Shapes/b2Shape.js \
--js ./jsBindings/Collision/Shapes/b2ChainShape.js \
--js ./jsBindings/Collision/Shapes/b2CircleShape.js \
--js ./jsBindings/Dynamics/b2Body.js \
--js ./jsBindings/Dynamics/b2World.js \
--js ./jsBindings/Dynamics/Joints/b2WheelJoint.js \
--js ./jsBindings/Dynamics/Joints/b2WeldJoint.js \
--js ./jsBindings/Dynamics/Joints/b2GearJoint.js \
--js ./jsBindings/Dynamics/Joints/b2Joint.js \
--js ./jsBindings/Dynamics/Joints/b2FrictionJoint.js \
--js ./jsBindings/Dynamics/Joints/b2RevoluteJoint.js \
--js ./jsBindings/Dynamics/Joints/b2MotorJoint.js \
--js ./jsBindings/Dynamics/Joints/b2PulleyJoint.js \
--js ./jsBindings/Dynamics/Joints/b2DistanceJoint.js \
--js ./jsBindings/Dynamics/Joints/b2PrismaticJoint.js \
--js ./jsBindings/Dynamics/Joints/b2RopeJoint.js \
--js ./jsBindings/Dynamics/Joints/b2MouseJoint.js \
--js ./jsBindings/Dynamics/Contacts/b2Contact.js \
--js ./jsBindings/Dynamics/b2Fixture.js \
--js ./jsBindings/Dynamics/b2WorldCallbacks.js \
--js ./jsBindings/Particle/b2ParticleSystem.js \
--js ./jsBindings/Particle/b2ParticleGroup.js \
--js ./jsBindings/Particle/b2Particle.js \
--js_output_file liquidfun.js
